### ISSUE TITLE
OpenLaters Viewer no attribute "resource"

### ISSUE THREAD

**Issue by benhid** [ckan/ckanext-geoview#63]
After installing the latest version of `ckanext-geoview` with `OpenLayers Viewer` (CKAN 2.8), the server produce the following exception:

```console
2019-10-29 13:54:00,074 ERROR [ckan.config.middleware.flask_app] 'werkzeug.local.LocalProxy object' has no attribute 'resource'
Traceback (most recent call last):
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan/venv/src/ckan/ckan/views/resource.py", line 585, in view
    return h.rendered_resource_view(view, resource, package, embed=True)
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/helpers.py", line 2303, in rendered_resource_view
    return literal(base.render(template, extra_vars=data_dict))
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/base.py", line 150, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/templating.py", line 140, in render_template
  ...
  File "/usr/lib/ckan/venv/src/ckan/ckan/templates/dataviewer/base.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/ckanext/geoview/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/venv/src/ckan/ckan/templates/base.html", line 106, in top-level template code
    {%- block page %}{% endblock -%}
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/ckanext/geoview/templates/dataviewer/openlayers2.html", line 9, in block "page"
    data-module-gapi_key="{{ gapi_key or c.resource.gapi_key }}"
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'werkzeug.local.LocalProxy object' has no attribute 'resource'
```

**Comment by benhid** [comment]
Fixed by installing the latest version from Github (0.0.16)
